package users;

import academic.Course;
import communication.Request;
import enums.Language;
import enums.ManagerType;
import java.io.Serializable;
import java.util.List;

public class Manager extends Employee implements Serializable {

	private static final long serialVersionUID = 1L;

	private ManagerType managerType;

	public Manager() {
	}

	public Manager(int id, String name, String email, String password, Language language, String employeeId,
			ManagerType managerType) {
		super(id, name, email, password, language, employeeId);
		this.managerType = managerType;
	}

	public void assignCourse(Teacher teacher, Course course) {
		teacher.getCourses().add(course);
		System.out.println("Course '" + course.getName() + "' assigned to " + teacher.getName());
	}

	public void approveRegistration(Student student) {
		System.out.println("Registration approved for: " + student.getName());
	}

	public void addCourseForRegistration(Course course) {
		System.out.println("Course added for registration: " + course.getName());
	}

	public void createStatisticalReport() {
		System.out.println("Statistical report generated by " + name);
	}

	public void manageNews() {
		System.out.println(name + " is managing news.");
	}

	public List<Student> viewStudentsInfo() {
		return null;
	}

	public List<Teacher> viewTeachersInfo() {
		return null;
	}

	public List<Request> viewEmployeeRequests() {
		return null;
	}

	public ManagerType getManagerType() {
		return managerType;
	}

	public void setManagerType(ManagerType managerType) {
		this.managerType = managerType;
	}

	@Override
	public String toString() {
		return "Manager{id=" + id + ", name='" + name + "', type=" + managerType + "}";
	}
}
